name: zendesk
description: Flutter interface for Zendesk Mobile SDK
version: 1.0.2
author: Jon Keating <jon@licq.org>
homepage: https://github.com/emostar/flutter-zendesk

flutter:
  plugin:
    androidPackage: com.codeheadlabs.zendesk
    pluginClass: ZendeskPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.4.0
  flutter_driver:
    sdk: flutter

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"
    