name: zendesk
description: Flutter interface for Zendesk Mobile SDK
version: 2.0.0
homepage: https://github.com/emostar/flutter-zendesk

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.5.0
  pigeon: ^0.1.9
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.codeheadlabs.zendesk
        pluginClass: ZendeskPlugin
      ios:
        pluginClass: ZendeskPlugin

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"
