name: zendesk
description: Flutter interface for Zendesk Mobile SDK
version: 2.0.1
homepage: https://github.com/emostar/flutter-zendesk

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pigeon: ^0.1.23

flutter:
  plugin:
    platforms:
      android:
        package: com.codeheadlabs.zendesk
        pluginClass: ZendeskPlugin
      ios:
        pluginClass: ZendeskPlugin

environment:
  sdk: '>=2.10.0 <3.0.0'